apiVersion: 1
datasources:
  - name: Research Prometheus
    uid: research-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 2s
